version: '3.1'

services:
  db:
    image: postgres:13.4
    privileged: true
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: 'myprojectuser'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: apipoint
