version: '3.1'

services:
  db:
    image: postgres:13.4
    privileged: true
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: 'myprojectuser'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: apipoint

  backend:
    build: ./DRF
    privileged: true
    ports:
      - 8080:8080
    command:
      - python3 manage.py migrate && manage.py runserver 0.0.0.0:8080

    depends_on:
      - db
