# Generated by Django 3.2.8 on 2021-11-03 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=254, null=True, unique=True, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Набор пользователей')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('mod_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('status', models.BooleanField(default=True, verbose_name='Создатель')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='ToDo.project', verbose_name='Набор пользователей')),
            ],
        ),
    ]
